/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCategory: typeof import('./src/components/category/AddCategory.vue')['default']
    AddClass: typeof import('./src/components/AddClass.vue')['default']
    AddRecord: typeof import('./src/components/data/AddRecord.vue')['default']
    AddSubCategory: typeof import('./src/components/category/AddSubCategory.vue')['default']
    AddSubclass: typeof import('./src/components/AddSubclass.vue')['default']
    AddTag: typeof import('./src/components/tag/AddTag.vue')['default']
    DeleteConfirm: typeof import('./src/components/DeleteConfirm.vue')['default']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FullScreenGraph: typeof import('./src/components/FullScreenGraph.vue')['default']
    Graph: typeof import('./src/components/Graph.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ModifyCategory: typeof import('./src/components/category/ModifyCategory.vue')['default']
    ModifyData: typeof import('./src/components/data/ModifyData.vue')['default']
    ModifyLabel: typeof import('./src/components/ModifyLabel.vue')['default']
    ModifyNumber: typeof import('./src/components/ModifyNumber.vue')['default']
    ModifySubCategory: typeof import('./src/components/category/ModifySubCategory.vue')['default']
    ModifyTag: typeof import('./src/components/tag/ModifyTag.vue')['default']
    RemoveTag: typeof import('./src/components/tag/RemoveTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
